Add note
Without this note, user will get error due to compression middleware compressing html before debug toolbar has been added to page.

`
500 Server Error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
`